# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DeviceCertificationProvisioningRequirement(Model):
    """DeviceCertificationProvisioningRequirement.

    :param provisioning_types:
    :type provisioning_types: list[str]
    """

    _attribute_map = {
        'provisioning_types': {'key': 'provisioningTypes', 'type': '[str]'},
    }

    def __init__(self, *, provisioning_types=None, **kwargs) -> None:
        super(DeviceCertificationProvisioningRequirement, self).__init__(**kwargs)
        self.provisioning_types = provisioning_types
