# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DeviceTestNotExistError(Model):
    """DeviceTestNotExistError.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param message:
    :type message: str
    :param code:
    :type code: int
    :ivar details:
    :vartype details: list[object]
    """

    _validation = {
        'details': {'readonly': True},
    }

    _attribute_map = {
        'message': {'key': 'message', 'type': 'str'},
        'code': {'key': 'code', 'type': 'int'},
        'details': {'key': 'details', 'type': '[object]'},
    }

    def __init__(self, **kwargs):
        super(DeviceTestNotExistError, self).__init__(**kwargs)
        self.message = kwargs.get('message', None)
        self.code = kwargs.get('code', None)
        self.details = None
