# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class InterfaceDefinitionSnapshot(Model):
    """InterfaceDefinitionSnapshot.

    :param interface_id:
    :type interface_id: str
    :param content:
    :type content: str
    :param resolution_source: Possible values include: 'Unknown',
     'GlobalRepository', 'PrivateRepository', 'UserUploads'
    :type resolution_source: str or ~swagger.models.enum
    """

    _attribute_map = {
        'interface_id': {'key': 'interfaceId', 'type': 'str'},
        'content': {'key': 'content', 'type': 'str'},
        'resolution_source': {'key': 'resolutionSource', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(InterfaceDefinitionSnapshot, self).__init__(**kwargs)
        self.interface_id = kwargs.get('interface_id', None)
        self.content = kwargs.get('content', None)
        self.resolution_source = kwargs.get('resolution_source', None)
