# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class IotEdgeCompatibleCertificationBadgeConfiguration(Model):
    """IotEdgeCompatibleCertificationBadgeConfiguration.

    All required parameters must be populated in order to send to Azure.

    :param os: Required.
    :type os: str
    :param type: Possible values include: 'IotDevice', 'Pnp',
     'IotEdgeCompatible'
    :type type: str or ~device_certification.models.enum
    """

    _validation = {
        'os': {'required': True},
    }

    _attribute_map = {
        'os': {'key': 'os', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(IotEdgeCompatibleCertificationBadgeConfiguration, self).__init__(**kwargs)
        self.os = kwargs.get('os', None)
        self.type = kwargs.get('type', None)
