# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class IotDeviceCertificationBadgeTestCases(Model):
    """IotDeviceCertificationBadgeTestCases.

    :param c2_dtests:
    :type c2_dtests: list[~swagger.models.C2DTest]
    :param d2_ctests:
    :type d2_ctests: list[~swagger.models.D2CTest]
    :param device_twin_tests:
    :type device_twin_tests: list[~swagger.models.DeviceTwinTest]
    :param direct_method_tests:
    :type direct_method_tests: list[~swagger.models.DirectMethodTest]
    :param type: Possible values include: 'IotDevice', 'Pnp',
     'IotEdgeCompatible'
    :type type: str or ~swagger.models.enum
    """

    _attribute_map = {
        'c2_dtests': {'key': 'c2DTests', 'type': '[C2DTest]'},
        'd2_ctests': {'key': 'd2CTests', 'type': '[D2CTest]'},
        'device_twin_tests': {'key': 'deviceTwinTests', 'type': '[DeviceTwinTest]'},
        'direct_method_tests': {'key': 'directMethodTests', 'type': '[DirectMethodTest]'},
        'type': {'key': 'type', 'type': 'str'},
    }

    def __init__(self, *, c2_dtests=None, d2_ctests=None, device_twin_tests=None, direct_method_tests=None, type=None, **kwargs) -> None:
        super(IotDeviceCertificationBadgeTestCases, self).__init__(**kwargs)
        self.c2_dtests = c2_dtests
        self.d2_ctests = d2_ctests
        self.device_twin_tests = device_twin_tests
        self.direct_method_tests = direct_method_tests
        self.type = type
