# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ModelDefinitionSnapshot(Model):
    """ModelDefinitionSnapshot.

    :param id:
    :type id: str
    :param content:
    :type content: str
    :param resolution_source: Possible values include: 'Unknown',
     'GlobalRepository', 'PrivateRepository', 'UserUploads'
    :type resolution_source: str or ~swagger.models.enum
    :param interface_snapshots:
    :type interface_snapshots:
     list[~swagger.models.InterfaceDefinitionSnapshot]
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'content': {'key': 'content', 'type': 'str'},
        'resolution_source': {'key': 'resolutionSource', 'type': 'str'},
        'interface_snapshots': {'key': 'interfaceSnapshots', 'type': '[InterfaceDefinitionSnapshot]'},
    }

    def __init__(self, **kwargs):
        super(ModelDefinitionSnapshot, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.content = kwargs.get('content', None)
        self.resolution_source = kwargs.get('resolution_source', None)
        self.interface_snapshots = kwargs.get('interface_snapshots', None)
