# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class NewTaskPayload(Model):
    """NewTaskPayload.

    :param task_type: Possible values include: 'QueueTestRun',
     'GenerateTestCases'
    :type task_type: str or ~swagger.models.enum
    """

    _attribute_map = {
        'task_type': {'key': 'taskType', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(NewTaskPayload, self).__init__(**kwargs)
        self.task_type = kwargs.get('task_type', None)
