# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PnpCertificationBadgeConfiguration(Model):
    """PnpCertificationBadgeConfiguration.

    :param digital_twin_model_definitions:
    :type digital_twin_model_definitions: list[str]
    :param type: Possible values include: 'IotDevice', 'Pnp',
     'IotEdgeCompatible'
    :type type: str or ~swagger.models.enum
    """

    _attribute_map = {
        'digital_twin_model_definitions': {'key': 'digitalTwinModelDefinitions', 'type': '[str]'},
        'type': {'key': 'type', 'type': 'str'},
    }

    def __init__(self, *, digital_twin_model_definitions=None, type=None, **kwargs) -> None:
        super(PnpCertificationBadgeConfiguration, self).__init__(**kwargs)
        self.digital_twin_model_definitions = digital_twin_model_definitions
        self.type = type
