# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PnpCertificationBadgeTestCases(Model):
    """PnpCertificationBadgeTestCases.

    :param model_definition_snapshot:
    :type model_definition_snapshot: ~swagger.models.ModelDefinitionSnapshot
    :param interface_tests:
    :type interface_tests: list[~swagger.models.InterfaceTest]
    :param type: Possible values include: 'IotDevice', 'Pnp',
     'IotEdgeCompatible'
    :type type: str or ~swagger.models.enum
    """

    _attribute_map = {
        'model_definition_snapshot': {'key': 'modelDefinitionSnapshot', 'type': 'ModelDefinitionSnapshot'},
        'interface_tests': {'key': 'interfaceTests', 'type': '[InterfaceTest]'},
        'type': {'key': 'type', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(PnpCertificationBadgeTestCases, self).__init__(**kwargs)
        self.model_definition_snapshot = kwargs.get('model_definition_snapshot', None)
        self.interface_tests = kwargs.get('interface_tests', None)
        self.type = kwargs.get('type', None)
